//! Owner Connection Bundle parsing and validation.
//!
//! The bundle is a plain-text key: value format generated by the Host Setup
//! view and pasted by the data owner into their Peer Storage tab.
//!
//! ## Format
//!
//! ```text
//! overlay_provider: tailscale
//! overlay_host:     peer.tailnet.ts.net
//! sftp_user:        nasbb-match-abc123
//! sftp_port:        22
//! sftp_path:        /repository
//! quota_gb:         500
//! match_id:         match-abc123
//!
//! # Verify via: ssh-keyscan -p PORT OVERLAY_HOST | ssh-keygen -lf -
//! # Both peers must be on the same Tailscale tailnet
//! ```
//!
//! Lines starting with `#` are comments and are ignored.
//! Blank lines are ignored.
//! Keys are case-insensitive and leading/trailing whitespace is stripped.

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// A parsed, validated Owner Connection Bundle.
/// Contains only non-secret fields — no private keys, no passwords.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PeerBundle {
    pub overlay_provider: String,
    pub overlay_host: String,
    pub sftp_user: String,
    pub sftp_port: u16,
    pub sftp_path: String,
    pub quota_gb: u64,
    pub match_id: String,
    /// Human-readable label set by the host. Optional for backward compatibility.
    #[serde(default)]
    pub connection_name: String,
    /// Placeholder text for host key fingerprint verification guidance.
    pub host_key_fingerprint_note: String,
    /// Compatibility guidance from the host.
    pub compatibility_note: String,
}

#[derive(Debug, Error, PartialEq)]
pub enum BundleParseError {
    #[error("bundle is empty or contains no parseable key: value lines")]
    EmptyBundle,
    #[error("missing required field: {0}")]
    MissingField(&'static str),
    #[error("sftp_port must be a number between 1 and 65535, got: '{0}'")]
    InvalidPort(String),
    #[error("quota_gb must be a positive number, got: '{0}'")]
    InvalidQuota(String),
    #[error("overlay_host must not be empty")]
    EmptyOverlayHost,
    #[error("sftp_user must not be empty")]
    EmptySftpUser,
    #[error("sftp_path must not be empty")]
    EmptySftpPath,
    #[error("match_id must not be empty")]
    EmptyMatchId,
}

/// Parse an Owner Connection Bundle from pasted text.
///
/// Accepts the `key: value` format produced by Host Setup. Lines beginning
/// with `#` are collected as notes; blank lines are skipped. Keys are matched
/// case-insensitively. Unknown keys are ignored (forward compatibility).
pub fn parse_bundle(text: &str) -> Result<PeerBundle, BundleParseError> {
    let mut map: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    let mut comment_lines: Vec<String> = Vec::new();
    let mut has_any_kv = false;

    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if trimmed.starts_with('#') {
            comment_lines.push(trimmed.trim_start_matches('#').trim().to_string());
            continue;
        }
        if let Some(colon) = trimmed.find(':') {
            let key = trimmed[..colon].trim().to_lowercase().replace(' ', "_");
            let value = trimmed[colon + 1..].trim().to_string();
            map.insert(key, value);
            has_any_kv = true;
        }
    }

    if !has_any_kv {
        return Err(BundleParseError::EmptyBundle);
    }

    let get = |field: &'static str| -> Result<String, BundleParseError> {
        map.get(field)
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .ok_or(BundleParseError::MissingField(field))
    };

    let overlay_host = get("overlay_host").map_err(|_| BundleParseError::EmptyOverlayHost)?;
    if overlay_host.is_empty() {
        return Err(BundleParseError::EmptyOverlayHost);
    }
    let sftp_user = get("sftp_user").map_err(|_| BundleParseError::EmptySftpUser)?;
    if sftp_user.is_empty() {
        return Err(BundleParseError::EmptySftpUser);
    }
    let sftp_path = get("sftp_path").map_err(|_| BundleParseError::EmptySftpPath)?;
    if sftp_path.is_empty() {
        return Err(BundleParseError::EmptySftpPath);
    }
    let match_id = get("match_id").map_err(|_| BundleParseError::EmptyMatchId)?;
    if match_id.is_empty() {
        return Err(BundleParseError::EmptyMatchId);
    }

    let port_str = map.get("sftp_port").map(|s| s.trim().to_string()).unwrap_or_else(|| "22".to_string());
    let sftp_port: u16 = port_str.parse().map_err(|_| BundleParseError::InvalidPort(port_str.clone()))?;
    if sftp_port == 0 {
        return Err(BundleParseError::InvalidPort(port_str));
    }

    let quota_str = map.get("quota_gb").map(|s| s.trim().to_string()).unwrap_or_else(|| "0".to_string());
    let quota_gb: u64 = quota_str.parse().map_err(|_| BundleParseError::InvalidQuota(quota_str.clone()))?;

    let overlay_provider = map
        .get("overlay_provider")
        .cloned()
        .unwrap_or_else(|| "not_configured".to_string());

    let connection_name = map
        .get("connection_name")
        .cloned()
        .unwrap_or_default();

    // First comment line often contains the fingerprint note
    let host_key_fingerprint_note = comment_lines
        .iter()
        .find(|l| l.to_lowercase().contains("verify") || l.to_lowercase().contains("fingerprint") || l.to_lowercase().contains("ssh-keyscan"))
        .cloned()
        .unwrap_or_else(|| "Verify host key fingerprint out-of-band before trusting this connection.".to_string());

    // Second comment line often contains the compatibility note
    let compatibility_note = comment_lines
        .iter()
        .find(|l| !l.to_lowercase().contains("verify") && !l.to_lowercase().contains("fingerprint") && !l.to_lowercase().contains("ssh-keyscan"))
        .cloned()
        .unwrap_or_default();

    Ok(PeerBundle {
        overlay_provider,
        overlay_host,
        sftp_user,
        sftp_port,
        sftp_path,
        quota_gb,
        match_id,
        connection_name,
        host_key_fingerprint_note,
        compatibility_note,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_bundle() -> &'static str {
        "overlay_provider: tailscale\n\
         overlay_host:     peer.tailnet.ts.net\n\
         sftp_user:        nasbb-match-abc123\n\
         sftp_port:        22\n\
         sftp_path:        /repository\n\
         quota_gb:         500\n\
         match_id:         match-abc123\n\
         \n\
         # Verify via: ssh-keyscan -p 22 peer.tailnet.ts.net | ssh-keygen -lf -\n\
         # Both peers must be on the same Tailscale tailnet"
    }

    #[test]
    fn parses_valid_bundle() {
        let b = parse_bundle(sample_bundle()).unwrap();
        assert_eq!(b.overlay_provider, "tailscale");
        assert_eq!(b.overlay_host, "peer.tailnet.ts.net");
        assert_eq!(b.sftp_user, "nasbb-match-abc123");
        assert_eq!(b.sftp_port, 22);
        assert_eq!(b.sftp_path, "/repository");
        assert_eq!(b.quota_gb, 500);
        assert_eq!(b.match_id, "match-abc123");
    }

    #[test]
    fn captures_fingerprint_note_from_comment() {
        let b = parse_bundle(sample_bundle()).unwrap();
        assert!(b.host_key_fingerprint_note.contains("ssh-keyscan") || b.host_key_fingerprint_note.contains("Verify"));
    }

    #[test]
    fn captures_compatibility_note_from_second_comment() {
        let b = parse_bundle(sample_bundle()).unwrap();
        assert!(b.compatibility_note.contains("tailnet") || b.compatibility_note.is_empty());
    }

    #[test]
    fn missing_overlay_host_is_rejected() {
        let text = "sftp_user: u\nsftp_path: /p\nmatch_id: m\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::EmptyOverlayHost)));
    }

    #[test]
    fn missing_sftp_user_is_rejected() {
        let text = "overlay_host: h\nsftp_path: /p\nmatch_id: m\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::EmptySftpUser)));
    }

    #[test]
    fn missing_sftp_path_is_rejected() {
        let text = "overlay_host: h\nsftp_user: u\nmatch_id: m\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::EmptySftpPath)));
    }

    #[test]
    fn missing_match_id_is_rejected() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::EmptyMatchId)));
    }

    #[test]
    fn empty_input_is_rejected() {
        assert!(matches!(parse_bundle(""), Err(BundleParseError::EmptyBundle)));
        assert!(matches!(parse_bundle("   \n\n"), Err(BundleParseError::EmptyBundle)));
        assert!(matches!(parse_bundle("# just a comment"), Err(BundleParseError::EmptyBundle)));
    }

    #[test]
    fn invalid_port_is_rejected() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\nsftp_port: abc\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::InvalidPort(_))));
    }

    #[test]
    fn zero_port_is_rejected() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\nsftp_port: 0\n";
        assert!(matches!(parse_bundle(text), Err(BundleParseError::InvalidPort(_))));
    }

    #[test]
    fn missing_port_defaults_to_22() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.sftp_port, 22);
    }

    #[test]
    fn missing_quota_defaults_to_zero() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.quota_gb, 0);
    }

    #[test]
    fn keys_are_case_insensitive() {
        let text = "OVERLAY_HOST: h\nSFTP_USER: u\nSFTP_PATH: /p\nMATCH_ID: m\n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.overlay_host, "h");
        assert_eq!(b.sftp_user, "u");
    }

    #[test]
    fn extra_whitespace_stripped_from_values() {
        let text = "overlay_host:   peer.example.com   \nsftp_user:  alice  \nsftp_path:  /repo  \nmatch_id:  match-1  \n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.overlay_host, "peer.example.com");
        assert_eq!(b.sftp_user, "alice");
    }

    #[test]
    fn unknown_keys_are_ignored() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\nunknown_future_field: whatever\n";
        assert!(parse_bundle(text).is_ok());
    }

    #[test]
    fn overlay_provider_defaults_to_not_configured() {
        let text = "overlay_host: h\nsftp_user: u\nsftp_path: /p\nmatch_id: m\n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.overlay_provider, "not_configured");
    }

    #[test]
    fn bundle_with_tabs_around_colon_parses() {
        let text = "overlay_host:\t peer.net\nsftp_user:\tu\nsftp_path:\t/p\nmatch_id:\tm\n";
        let b = parse_bundle(text).unwrap();
        assert_eq!(b.overlay_host, "peer.net");
    }
}
